<?php

namespace Fuel\Migrations;

class Update_print_prices
{
	public function up()
	{
		include_once '006_create_print_prices.php';
		call_user_func(array(new Create_print_prices, 'down'));
		
		\DBUtil::create_table('print_prices', array(
			'id' => array('constraint' => 11, 'type' => 'int', 'auto_increment' => true, 'unsigned' => true),
			'size' => array('constraint' => 8, 'type' => 'varchar'),
			'color' => array('constraint' => 11, 'type' => 'int'),
			'duplex' => array('constraint' => 11, 'type' => 'int'),
			'paper_weight' => array('constraint' => 16, 'type' => 'varchar', 'null' => true),
			'number' => array('constraint' => 11, 'type' => 'int'),
			'price' => array('type' => 'float'),

		), array('id'));
		
		// 印刷 １色
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>     0, 'duplex' => 0, 'price' =>  8  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   100, 'duplex' => 0, 'price' =>  7  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   300, 'duplex' => 0, 'price' =>  6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   500, 'duplex' => 0, 'price' =>  5  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  1000, 'duplex' => 0, 'price' =>  4  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  3000, 'duplex' => 0, 'price' =>  3.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  5000, 'duplex' => 0, 'price' =>  3  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' => 10000, 'duplex' => 0, 'price' =>  2.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' => 20000, 'duplex' => 0, 'price' =>  2  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>     0, 'duplex' => 1, 'price' => 13.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   100, 'duplex' => 1, 'price' => 11.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   300, 'duplex' => 1, 'price' => 10.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>   500, 'duplex' => 1, 'price' =>  8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  1000, 'duplex' => 1, 'price' =>  6.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  3000, 'duplex' => 1, 'price' =>  6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' =>  5000, 'duplex' => 1, 'price' =>  5.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' => 10000, 'duplex' => 1, 'price' =>  4.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B5', 'number' => 20000, 'duplex' => 1, 'price' =>  3.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>     0, 'duplex' => 0, 'price' =>  8  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   100, 'duplex' => 0, 'price' =>  7  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   300, 'duplex' => 0, 'price' =>  6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   500, 'duplex' => 0, 'price' =>  5  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  1000, 'duplex' => 0, 'price' =>  4  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  3000, 'duplex' => 0, 'price' =>  3.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  5000, 'duplex' => 0, 'price' =>  3  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' => 10000, 'duplex' => 0, 'price' =>  2.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' => 20000, 'duplex' => 0, 'price' =>  2  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>     0, 'duplex' => 1, 'price' => 13.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   100, 'duplex' => 1, 'price' => 11.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   300, 'duplex' => 1, 'price' => 10.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>   500, 'duplex' => 1, 'price' =>  8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  1000, 'duplex' => 1, 'price' =>  6.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  3000, 'duplex' => 1, 'price' =>  6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' =>  5000, 'duplex' => 1, 'price' =>  5.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' => 10000, 'duplex' => 1, 'price' =>  4.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A4', 'number' => 20000, 'duplex' => 1, 'price' =>  3.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>     0, 'duplex' => 0, 'price' => 10  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   100, 'duplex' => 0, 'price' =>  9  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   300, 'duplex' => 0, 'price' =>  8  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   500, 'duplex' => 0, 'price' =>  7  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  1000, 'duplex' => 0, 'price' =>  5.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  3000, 'duplex' => 0, 'price' =>  4.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  5000, 'duplex' => 0, 'price' =>  3.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' => 10000, 'duplex' => 0, 'price' =>  3  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' => 20000, 'duplex' => 0, 'price' =>  2.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>     0, 'duplex' => 1, 'price' => 17  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   100, 'duplex' => 1, 'price' => 15.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   300, 'duplex' => 1, 'price' => 13.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>   500, 'duplex' => 1, 'price' => 11.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  1000, 'duplex' => 1, 'price' =>  9.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  3000, 'duplex' => 1, 'price' =>  7.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' =>  5000, 'duplex' => 1, 'price' =>  6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' => 10000, 'duplex' => 1, 'price' =>  5.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'B4', 'number' => 20000, 'duplex' => 1, 'price' =>  4.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>     0, 'duplex' => 0, 'price' => 11.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   100, 'duplex' => 0, 'price' => 10.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   300, 'duplex' => 0, 'price' =>  9.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   500, 'duplex' => 0, 'price' =>  8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  1000, 'duplex' => 0, 'price' =>  7.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  3000, 'duplex' => 0, 'price' =>  6.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  5000, 'duplex' => 0, 'price' =>  5.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' => 10000, 'duplex' => 0, 'price' =>  4.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' => 20000, 'duplex' => 0, 'price' =>  3.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>     0, 'duplex' => 1, 'price' => 19.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   100, 'duplex' => 1, 'price' => 17.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   300, 'duplex' => 1, 'price' => 16.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>   500, 'duplex' => 1, 'price' => 14.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  1000, 'duplex' => 1, 'price' => 12.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  3000, 'duplex' => 1, 'price' => 11.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' =>  5000, 'duplex' => 1, 'price' =>  9.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' => 10000, 'duplex' => 1, 'price' =>  7.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 0, 'size' => 'A3', 'number' => 20000, 'duplex' => 1, 'price' =>  6  ))->execute();

		// 印刷 カラー 紙厚さ90kg
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  54  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  27.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  26.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  26.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  16  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  11.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  10.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   7.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   5.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   4.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   4.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  70  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  38.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  37.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  37.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  22.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  16  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  12.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  10.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   9.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   9.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   8.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   7.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   6.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   6.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  54  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  27.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  26.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  26.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  16  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  11.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  10.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   7.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   6  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   5.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   4.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   4.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  70  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  38.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  37.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  37.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  22.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  16  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  12.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  10.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   9.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   9.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   8.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   8.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   7.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   6.7))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>   6.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 90, 'price' => 128  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  79  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  52.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  31.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  20.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  20.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  18  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  15.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  14.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  13.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  12.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  12.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  11.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  10.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   8.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 90, 'price' => 187.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  94.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  74.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  44.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  30.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  30.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  23.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  20.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  18.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  17.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  16.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  15.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  14.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  12.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  11.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 90, 'price' => 128  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  79  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  52.1))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  31.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  20.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  20.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  18  ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  15.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  14.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  13.4))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  12.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  12.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  11.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>  10.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 90, 'price' =>   8.8))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 90, 'price' => 187.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  94.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  74.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  44.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  30.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  30.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  23.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  20.5))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  18.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  17.2))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  16.3))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  15.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  14.6))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  12.9))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 90, 'price' =>  11.4))->execute();

		// 印刷 カラー 紙厚さ110kg
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>     0, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  80   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  40.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  27.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  20.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  16.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  15.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   600, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  14.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   700, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   800, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   900, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  6000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  6500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  7000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  7500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  8000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  8500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  9000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  9500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 11000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 12000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 13000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 14000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 15000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 16000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 17000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 18000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 19000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 21000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 22000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 23000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 24000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 25000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 26000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 27000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 28000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 29000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 30000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 35000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 40000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 45000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>     0, 'duplex' => 1, 'paper_weight' => 110, 'price' => 112   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  56.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  38   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  30.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  23.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  22   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   600, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  21.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   700, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  20.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   800, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  20   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>   900, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  19.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  10.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  10.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  4500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  10.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  10   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  5500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  6000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  6500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  7000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  7500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  8000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  8500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  9000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' =>  9500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 11000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 12000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 13000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 14000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 15000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 16000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 17000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 18000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 19000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 21000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 22000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 23000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 24000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 25000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 26000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 27000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 28000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 29000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 30000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 35000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 40000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A4', 'number' => 45000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>     0, 'duplex' => 0, 'paper_weight' => 110, 'price' => 168   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  85   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  57.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  43.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  35.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  31.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   600, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  28.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   700, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  26.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   800, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  25.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   900, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  23.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  19.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  17.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  16   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  15.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  14.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  14.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  13   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  6000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  6500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  7000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  7500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  8000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  8500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  9000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  9500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 11000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 12000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 13000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 14000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 15000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 16000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 17000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 18000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 19000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 21000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 22000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 23000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 24000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 25000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 26000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 27000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 28000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 29000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 30000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 35000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 40000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 45000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>     0, 'duplex' => 1, 'paper_weight' => 110, 'price' => 298   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 110, 'price' => 150   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 110, 'price' => 100.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  76   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  61.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  52.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   600, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  46.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   700, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  41.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   800, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  38   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>   900, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  35.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  27.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  23.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  21.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  20.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  19.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  18.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  17.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  4500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  17.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  16.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  5500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  16.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  6000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  16   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  6500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  7000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  7500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  8000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  8500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  9000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' =>  9500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 11000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 12000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 13000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 14000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 15000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.7 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 16000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.6 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 17000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.5 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 18000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 19000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 21000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 22000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.2 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 23000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 24000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.1 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 25000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 26000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 27000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13   ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 28000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 29000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 30000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.8 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 35000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.4 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 40000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.9 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'A3', 'number' => 45000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.3 ))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>     0, 'duplex' => 0, 'paper_weight' => 110, 'price' => 127.50))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  65.10))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  44.20))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  33.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  27.48))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  25.05))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   600, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  23.31))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   700, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  22.05))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   800, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  21.03))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   900, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  20.22))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  16.16))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  14.13))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.90))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.09))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.92))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.80))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.69))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.62))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.27))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  11.00))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  6000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  6500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.55))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  7000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.37))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  7500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.22))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  8000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.08))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  8500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.96))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  9000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.85))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  9500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.60))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 11000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.47))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 12000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.36))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 13000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.27))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 14000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.19))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 15000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.12))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 16000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.06))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 17000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   9.01))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 18000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.96))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 19000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.91))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.87))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 21000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.84))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 22000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.80))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 23000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.77))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 24000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.74))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 25000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.72))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 26000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.69))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 27000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.67))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 28000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.65))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 29000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.63))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 30000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.53))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 35000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.45))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 40000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.39))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 45000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.34))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>     0, 'duplex' => 1, 'paper_weight' => 110, 'price' => 187.20))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  98.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  69.10))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  54.38))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  45.48))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  39.65))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   600, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  35.49))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   700, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  32.40))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   800, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  29.97))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>   900, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  28.02))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  22.04))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  19.07))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  17.27))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  16.07))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.43))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.94))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.57))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  4500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.26))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.21))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  5500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.17))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  6000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.13))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  6500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.10))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  7000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.06))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  7500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.05))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  8000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.03))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  8500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.01))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  9000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.00))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' =>  9500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.98))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 11000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.47))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 12000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.27))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 13000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  13.10))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 14000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.95))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 15000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.82))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 16000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 17000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.61))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 18000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.52))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 19000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.44))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.36))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 21000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.29))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 22000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.23))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 23000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.18))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 24000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.13))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 25000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.08))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 26000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  12.03))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 27000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.99))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 28000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.96))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 29000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.92))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 30000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.88))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 35000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.86))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 40000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.84))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B4', 'number' => 45000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.82))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>     0, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  41.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   100, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  22.35))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   200, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  15.90))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   300, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  12.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   400, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.92))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.80))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   600, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   700, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.61))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   800, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.57))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   900, 'duplex' => 0, 'paper_weight' => 110, 'price' =>  10.53))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   8.64))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   7.12))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.74))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.48))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.28))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.13))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   6.00))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.84))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  6000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.60))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  6500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.50))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  7000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.42))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  7500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.35))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  8000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.28))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  8500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.23))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  9000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.18))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  9500, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.13))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 10000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.07))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 11000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   5.02))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 12000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.98))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 13000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.95))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 14000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.92))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 15000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.89))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 16000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.87))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 17000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.84))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 18000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.83))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 19000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.81))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 20000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.79))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 21000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.78))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 22000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.77))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 23000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 24000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.74))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 25000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.73))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 26000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.72))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 27000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.72))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 28000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 29000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 30000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.62))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 35000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.56))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 40000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.51))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 45000, 'duplex' => 0, 'paper_weight' => 110, 'price' =>   4.47))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>     0, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  92.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   100, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  48.00))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   200, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  33.10))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   300, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  25.80))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   400, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  21.42))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  19.20))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   600, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  17.57))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   700, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  16.39))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   800, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  15.43))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>   900, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  14.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>  11.46))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  1500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   9.63))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.86))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  2500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   8.21))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.64))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  3500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   7.21))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.87))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  4500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.60))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.62))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  5500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.64))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  6000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.66))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  6500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.67))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  7000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.68))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  7500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.69))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  8000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.70))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  8500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  9000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.71))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' =>  9500, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.72))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 10000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.60))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 11000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.51))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 12000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.42))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 13000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.35))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 14000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.29))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 15000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.24))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 16000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.19))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 17000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.15))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 18000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.11))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 19000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.08))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 20000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.17))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 21000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.26))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 22000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.35))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 23000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.80))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 24000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.49))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 25000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.56))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 26000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.62))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 27000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.67))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 28000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.72))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 29000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.75))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 30000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.59))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 35000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.47))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 40000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.38))->execute();
		\DB::insert('print_prices')->set(array('color' => 1, 'size' => 'B5', 'number' => 45000, 'duplex' => 1, 'paper_weight' => 110, 'price' =>   6.30))->execute();

	}

	public function down()
	{
		\DBUtil::drop_table('print_prices');
		
		include_once '006_create_print_prices.php';
		call_user_func(array(new Create_print_prices, 'up'));
	}
}